/**
 * Part of test
 * Created by: @Author V
 * Date: @Date 04-Jun-22
 * Time: 21:10
 * =============================================================
 **/

package com.omicron.organizerb.model;

import javafx.beans.property.StringProperty;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;

@Data
public class Task {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String title;

    private String description;

    private List<Task> subTasks;

    private boolean repeat;

    private LocalDate date;

    private LocalTime time;

    private TaskPriority priority;

    private List<String> tags;

    // ========================================================================================
    // Constructors
    // ========================================================================================

    public Task(String title, String description, List<Task> subTasks, boolean repeat, LocalDate date, LocalTime time, TaskPriority priority, List<String> tags) {
        this.title = title;
        this.description = description;
        this.subTasks = subTasks;
        this.repeat = repeat;
        this.date = date;
        this.time = time;
        this.priority = priority;
        this.tags = tags;
    }

    public Task(String title) {
        this.title = title;
    }

    public Task() {
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by Lombok

    // ========================================================================================
    // Methods
    // ========================================================================================


    @Override
    public String toString() {
        return title;
    }

    public String toStringFullDetails() {
        return "Task{" +
                "title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", subTasks=" + subTasks +
                ", repeat=" + repeat +
                ", date=" + date +
                ", time=" + time +
                ", priority=" + priority +
                ", tags=" + tags +
                '}';
    }
}
