/**
 * Part of OrganizerB
 * Created by: @Author V
 * Date: @Date 08-Jun-22
 * Time: 13:36
 * =============================================================
 **/

package com.omicron.organizerb.model;

import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Data
public class TaskList {

    // ========================================================================================
    // Fields
    // ========================================================================================

    private String taskListTitle;

    private List<Task> tasks = new ArrayList<>();


    // ========================================================================================
    // Constructors
    // ========================================================================================

    public TaskList(String taskListTitle) {
        this.taskListTitle = taskListTitle;
    }

    public TaskList(String taskListTitle, List<Task> tasks) {
        this.taskListTitle = taskListTitle;
        this.tasks = tasks;
    }

    public TaskList() {
        this.tasks = new ArrayList<>();
    }

    // ========================================================================================
    // Getters & Setters
    // ========================================================================================

    // generated by Lombok

    // ========================================================================================
    // Methods
    // ========================================================================================

    public void addTask(Task task) {
        tasks.add(task);
    }

    public Task getTask(int index) {
       return tasks.get(index);
    }

    @Override
    public String toString() {
        return taskListTitle;
    }
}
